### ISSUE TITLE
Distro options

### ISSUE THREAD

**Issue by vaisov** [xetys/hetzner-kube#184] opened 2018-09-05 13:14 UTC
Just curious why Ubuntu was chosen over Debian or even CoreOS?

**Comment by xetys** [comment] 2018-09-05 14:14
First of all, all that I write is my opinion and taste and feel free to correct me.

Why not Debian? Debian is my first distro and over time my favorite one because of its maturity and stability. However, I faced a lot of issues while playing with cutting edge of Debian, because it's not the home of cutting edge and doing that, can make things less stable.

Why not CoreOS? At the first time, I was totally thrilled about CoreOS, as of its container-centric philosophy and with CoreOS I learned how to use systemd in a way I like. However, when it came into practice, I learned a lot of problems caused by its little age and maturity. I had several issues with different network adapters, floating IPs when doing that on ProfitBricks. 
In general, it felt like CoreOS is a good idea if you need a strategy of operating several clusters with several hundreds of instances.

Ubuntu is one step before cutting edge. So you have all the recent stuff baked by upstream developers, while it's not too new so it breaks all the time.  I learned that it's a better idea to live the CoreOS philosophy while doing that on Ubuntu.

And not 18.04, but 16.04. Ubuntu needs its time to make their current LTS version really stable. I started using 16.04 not before 2017 and was fully relying on 14.04, as it was far more stable. I assume, in 2019 I will take a closer look at 18.04 again. Today, it is not really stable. Check out #154 for more details

**Comment by vaisov** [comment] 2018-09-05 14:31
Whoah! Thank a lot for so comprehensive reply, appreciate that! :)
By the way, is it possible to provide the desired kubernetes version as argument or it won't work so easily as lots of things could change between versions? Also what about upgrade, any plans to integrate such functionality?

**Comment by smirnov-mi** [comment] 2018-09-24 13:10
Very good points on stability, xetys. Still, would it be possible to add an argument for choosing host OS ?   Something like --os ub16 / ub18 / fed27 / fed28 / deb9 / cent7  or similar.

**Comment by xetys** [comment] 2019-01-29 12:54
after having some hard work on ubu18, currently, this option would cause some real developing overhead.

The current design is stuck to a concrete distro, which for now is ubuntu 18. Having the option to choose different distros would be a good thing from the user side. But on the other side this means:

1. the code structure must be changed to enable easy customizing for each distro. Currently, we do similar things with the add-on system, where there is code you can use or inherit, but specify on details. 
2. supporting multiple distros makes us responsible to keep all those options working, instead of just care about one. So for future releases, there would be a lot more code to support.

This leads to a huge amount of work for a benefit, I personally don't really get. For me, it is better to have a tool which does one specialized thing well, rather fit multiple options and continuously fail on some of them. That is, as the team working on hetzner-kube is not so big and we have a few capacities and already a lot of stuff to do.

As I don't plan to work in this direction, I close the issue here. If something is left to being discussed, feel free to open it again.

**Closed by xetys** 2019-01-29 12:54 UTC
