### ISSUE TITLE
Adding worker node crashes on OSX (0.3.1-SNAPSHOT)

### ISSUE THREAD

**Issue by vschwaberow** [xetys/hetzner-kube#148] opened 2018-06-16 11:28 UTC
```
$ hetzner-kube cluster add-worker --nodes 1 --name iridescent-foerune
2018/06/16 13:26:13 creating server 'iridescent-foerune-worker-02'...
  --- [======================================] 100%
2018/06/16 13:26:36 Created node 'iridescent-foerune-worker-02' with IP *.*.*.*
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/xetys/hetzner-kube/pkg/clustermanager.PrivateIPPrefix(0x0, 0x0, 0xc42015b668, 0x2)
	/Users/volkerschwaberow/golang/src/github.com/xetys/hetzner-kube/pkg/clustermanager/wireguard.go:64 +0xad
github.com/xetys/hetzner-kube/pkg/hetzner.(*Provider).CreateNodes(0xc4200e8400, 0x14ff9b1, 0x6, 0x0, 0x0, 0x14fdb62, 0x4, 0x0, 0x0, 0x0, ...)
	/Users/volkerschwaberow/golang/src/github.com/xetys/hetzner-kube/pkg/hetzner/hetzner_provider.go:110 +0x675
github.com/xetys/hetzner-kube/pkg/hetzner.(*Provider).CreateWorkerNodes(0xc4200e8400, 0xc4201b1448, 0x3, 0x14fdb62, 0x4, 0xc4201be6c0, 0x3, 0x3, 0x1, 0x1, ...)
	/Users/volkerschwaberow/golang/src/github.com/xetys/hetzner-kube/pkg/hetzner/hetzner_provider.go:146 +0x14b
github.com/xetys/hetzner-kube/cmd.glob..func5(0x17c2e20, 0xc4200b0fc0, 0x0, 0x4)
	/Users/volkerschwaberow/golang/src/github.com/xetys/hetzner-kube/cmd/cluster_add_worker.go:102 +0x5e5
github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra.(*Command).execute(0x17c2e20, 0xc4200b0f40, 0x4, 0x4, 0x17c2e20, 0xc4200b0f40)
	/Users/volkerschwaberow/golang/src/github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x17c5020, 0x177c960, 0x0, 0x0)
	/Users/volkerschwaberow/golang/src/github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra.(*Command).Execute(0x17c5020, 0x14fe4a5, 0x5)
	/Users/volkerschwaberow/golang/src/github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/xetys/hetzner-kube/cmd.Execute()
	/Users/volkerschwaberow/golang/src/github.com/xetys/hetzner-kube/cmd/root.go:51 +0x7e
main.main()
	/Users/volkerschwaberow/golang/src/github.com/xetys/hetzner-kube/main.go:20 +0x20
```

**Comment by JohnnyQQQQ** [comment] 2018-06-16 20:43
I can't reproduce the problem with the current master branch.

**Comment by JohnnyQQQQ** [comment] 2018-06-17 12:43
Which commit are you building from?

**Comment by lbvffvbl** [comment] 2018-06-18 08:50
the same problem with current master branch

**Comment by JohnnyQQQQ** [comment] 2018-06-18 08:53
Seems to be darwin specific then. Feel free to debug an open an pr.

**Comment by lbvffvbl** [comment] 2018-06-18 09:34
no, its ubuntu 16.04, with go get -u github.com/xetys/hetzner-kube

**Comment by lbvffvbl** [comment] 2018-06-18 11:36
as i see in my config file value of node_cidr is empty. but "github.com/xetys/hetzner-kube/pkg/clustermanager.PrivateIPPrefix" got this empty value as ip in hetzner_provider.go:

cidrPrefix := clustermanager.PrivateIPPrefix(provider.nodeCidr)

and trying to 
strings.Join(strings.Split(ip, ".")[:3], ".")

**Comment by JohnnyQQQQ** [comment] 2018-06-18 11:39
Ah nice catch, I had the same issue. You just need to edit it and add "10.0.1.0/24" to it. IIRC it's a bug caused when saving the config in an older version that is fixed now.

**Comment by JohnnyQQQQ** [comment] 2018-06-18 11:40
The congif can be found here `~/.hetzner-kube/config.json`

**Comment by lbvffvbl** [comment] 2018-06-18 11:42
i trying to create cluster with new version and deleting config file and node_cidr still was empty

**Comment by JohnnyQQQQ** [comment] 2018-06-18 11:43
Okay, fair enough

**Comment by trippinCode** [comment] 2018-06-29 12:56
It seems like i'm having the same issue on a ubuntu 18.04 pc.
I don't have a node_cidr entry at all in my config file, where do i need to put it. 

```
root@computer:/some/path/# hetzner-kube cluster add-worker --name test-cluster -n 1
Enter passphrase for SSH key /root/.ssh/id_rsa: 
2018/06/29 14:38:32 creating server 'test-cluster-worker-02'...
  --- [======================================] 100%
2018/06/29 14:38:55 Created node 'test-cluster-worker-02' with IP 159.69.48.138
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/xetys/hetzner-kube/pkg/clustermanager.PrivateIPPrefix(0x0, 0x0, 0xc420133560, 0x2)
	/root/go/src/github.com/xetys/hetzner-kube/pkg/clustermanager/wireguard.go:64 +0xad
github.com/xetys/hetzner-kube/pkg/hetzner.(*Provider).CreateNodes(0xc4200c0480, 0x8ffc4a, 0x6, 0x0, 0x0, 0x8fdde2, 0x4, 0x0, 0x0, 0x0, ...)
	/root/go/src/github.com/xetys/hetzner-kube/pkg/hetzner/hetzner_provider.go:110 +0x675
github.com/xetys/hetzner-kube/pkg/hetzner.(*Provider).CreateWorkerNodes(0xc4200c0480, 0xc420187550, 0x7, 0x8fdde2, 0x4, 0xc4201926f0, 0x3, 0x3, 0x1, 0x1, ...)
	/root/go/src/github.com/xetys/hetzner-kube/pkg/hetzner/hetzner_provider.go:146 +0x14b
github.com/xetys/hetzner-kube/cmd.glob..func5(0xbc1080, 0xc42006f040, 0x0, 0x4)
	/root/go/src/github.com/xetys/hetzner-kube/cmd/cluster_add_worker.go:102 +0x5e5
github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra.(*Command).execute(0xbc1080, 0xc42006efc0, 0x4, 0x4, 0xbc1080, 0xc42006efc0)
	/root/go/src/github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xbc34a0, 0xb7a9e0, 0x0, 0x0)
	/root/go/src/github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra.(*Command).Execute(0xbc34a0, 0x8fe72e, 0x5)
	/root/go/src/github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/xetys/hetzner-kube/cmd.Execute()
	/root/go/src/github.com/xetys/hetzner-kube/cmd/root.go:51 +0x7e
main.main()
	/root/go/src/github.com/xetys/hetzner-kube/main.go:20 +0x20

```

**Comment by trippinCode** [comment] 2018-07-09 12:53
@JohnnyQQQQ 
maybe you could tell me where i need to put the node_cidr in the ~/.hetzner-kube/config.json?

**Comment by voron** [comment] 2018-08-05 04:36
@trippinCode I was able to "fix" it specifying node_cidr at the end of config, like following (output formatted by `jq` to pretty look, real config.json isn't formatted) :
```
      "ha_enabled": false,
      "isolated_etcd": false,
      "self_hosted": false,
      "cloud_init_file": "",
      "node_cidr": "10.0.1.0/24"
    }
  ]
}
```

**Comment by mavimo** [comment] 2018-10-27 18:44
I'm going to close it since should be already fixed

**Closed by mavimo** 2018-10-27 18:44 UTC
Labels: bug, platform: OSX
