### ISSUE TITLE
Cluster add-worker panic runtime error

### ISSUE THREAD

**Issue by kabudu** [xetys/hetzner-kube#207] opened 2018-10-20 17:46 UTC
Hetzner Kube version: `0.3.1-RELEASE` (output of `hetzner-kube version`)
OS: `Fedora release 26`
Go version: `go version go1.8.7 linux/amd64`

Just tried to add a worker to my cluster using the following command:

`hetzner-kube cluster add-worker --datacenters fsn1-dc8 --name prod-general --nodes 1 --worker-server-type cx21-ceph` and had the following panic runtime error:

```
2018/10/20 18:35:18 creating server 'prod-general-worker-02'...
  --- [======================================] 100%
2018/10/20 18:35:39 Created node 'prod-general-worker-02' with IP XX.XX.XXX.XXX
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/xetys/hetzner-kube/pkg/clustermanager.PrivateIPPrefix(0x0, 0x0, 0xc4201094a0, 0x2)
        /home/david/go-path/src/github.com/xetys/hetzner-kube/pkg/clustermanager/wireguard.go:64 +0xad
github.com/xetys/hetzner-kube/pkg/hetzner.(*Provider).CreateNodes(0xc420098600, 0x91b2c7, 0x6, 0x0, 0x0, 0x7ffe41aac500, 0x9, 0x0, 0x0, 0x0, ...)
        /home/david/go-path/src/github.com/xetys/hetzner-kube/pkg/hetzner/hetzner_provider.go:110 +0x6b9
github.com/xetys/hetzner-kube/pkg/hetzner.(*Provider).CreateWorkerNodes(0xc420098600, 0xc42015f550, 0xd, 0x7ffe41aac500, 0x9, 0xc4200475b0, 0x1, 0x1, 0x1, 0x1, ...)
        /home/david/go-path/src/github.com/xetys/hetzner-kube/pkg/hetzner/hetzner_provider.go:146 +0x14b
github.com/xetys/hetzner-kube/cmd.glob..func5(0xbdb3e0, 0xc420098580, 0x0, 0x8)
        /home/david/go-path/src/github.com/xetys/hetzner-kube/cmd/cluster_add_worker.go:102 +0x845
github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra.(*Command).execute(0xbdb3e0, 0xc420098500, 0x8, 0x8, 0xbdb3e0, 0xc420098500)
        /home/david/go-path/src/github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xbdd800, 0xb95680, 0x0, 0x0)
        /home/david/go-path/src/github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra.(*Command).Execute(0xbdd800, 0x919dc3, 0x5)
        /home/david/go-path/src/github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/xetys/hetzner-kube/cmd.Execute()
        /home/david/go-path/src/github.com/xetys/hetzner-kube/cmd/root.go:51 +0x82
main.main()
        /home/david/go-path/src/github.com/xetys/hetzner-kube/main.go:20 +0x20
```

Checking in the hetzner console, I can see that the node has been created, but I'm guessing that it has not been correctly configured because of the error. I have verified the non-configuration via my monitoring tools and the lack of the docker runtime on the new node.

Any ideas?

**Comment by JohnnyQQQQ** [comment] 2018-10-20 19:33
Duplicate of #148

**Closed by JohnnyQQQQ** 2018-10-20 19:33 UTC
